# Generated by Django 5.0.1 on 2024-01-24 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home/banner_images/')),
            ],
            options={
                'verbose_name_plural': '08. Banner',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/Categorie/Img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '02. Categorie',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '09. Contact',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '06. Coupon',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo_file', models.ImageField(upload_to='logo_files/')),
                ('background_image', models.ImageField(upload_to='Banner/background')),
                ('nav_image', models.ImageField(upload_to='Banner/nav')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile_number', models.BigIntegerField(unique=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '07. Logo',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('image', models.ImageField(null=True, upload_to='Media/Product/Img/')),
                ('image_2nd', models.ImageField(blank=True, default=None, null=True, upload_to='Media/Product/Img/')),
                ('image_3rd', models.ImageField(blank=True, default=None, null=True, upload_to='Media/Product/Img/')),
                ('image_4th', models.ImageField(blank=True, default=None, null=True, upload_to='Media/Product/Img/')),
                ('image_5th', models.ImageField(blank=True, default=None, null=True, upload_to='Media/Product/Img/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra-Small', 'Extra-Small'), ('Extra-Large', 'Extra-Large'), ('Double-Extra-Large', 'Double-Extra-Large'), ('Triple-Extra-Large', 'Triple-Extra-Large'), ('Petite', 'Petite'), ('Regular', 'Regular'), ('Tall', 'Tall'), ('Short', 'Short'), ('Plus-Size', 'Plus-Size'), ('Oversize', 'Oversize'), ('Full-Length', 'Full-Length'), ('Half-Length', 'Half-Length')], max_length=100)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('White', 'White'), ('Black', 'Black'), ('Cyan', 'Cyan'), ('Maroon', 'Maroon'), ('Olive', 'Olive'), ('Gold', 'Gold')], max_length=100)),
                ('level', models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': '04. Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '01. User',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bluewatermarines.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.product')),
            ],
            options={
                'verbose_name_plural': '05. OrderItem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='bluewatermarines.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.product')),
            ],
            options={
                'verbose_name_plural': 'Order Items Success',
            },
        ),
        migrations.CreateModel(
            name='Product_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dimensions', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Guarantee', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Brand', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Item_model_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Item_Type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Item_Height', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Item_Width', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Item_Weight', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/SubCategorie/Img')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('parent_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.categorie')),
            ],
            options={
                'verbose_name_plural': '03.SubCategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluewatermarines.subcategorie'),
        ),
    ]
