# Generated by Django 5.0.1 on 2024-01-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluewatermarines', '0002_thirdcategorie_alter_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '10. Banner'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': '11. Contact'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name_plural': '09. Logo'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '08. Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '07. OrderItem'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '05. Product'},
        ),
    ]
