# Generated by Django 5.0.1 on 2024-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluewatermarines', '0003_alter_banner_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra-Small', 'Extra-Small'), ('Extra-Large', 'Extra-Large'), ('Double-Extra-Large', 'Double-Extra-Large'), ('Triple-Extra-Large', 'Triple-Extra-Large'), ('Petite', 'Petite'), ('Regular', 'Regular'), ('Tall', 'Tall'), ('Short', 'Short'), ('Plus-Size', 'Plus-Size'), ('Oversize', 'Oversize'), ('Full-Length', 'Full-Length'), ('Half-Length', 'Half-Length')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('White', 'White'), ('Black', 'Black'), ('Cyan', 'Cyan'), ('Maroon', 'Maroon'), ('Olive', 'Olive'), ('Gold', 'Gold')], default=None, max_length=100, null=True),
        ),
    ]
